name: recipe_app
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^4.7.0
  equatable: ^2.0.5
  flutter_dotenv: ^5.0.2
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  lottie: ^1.4.3
  cached_network_image: ^3.2.2
  google_fonts: ^3.0.1
  auto_route: ^5.0.1
  isar: ^3.0.1
  isar_flutter_libs: ^3.0.1
  flutter_riverpod: ^2.0.2
  live_activities: ^1.0.0
  flutter_local_notifications: ^12.0.2
  flutter_rating_bar: ^4.0.1
  flutter_native_splash: ^2.2.14
  flutter_svg: ^1.1.5
  file_picker: ^5.2.2

  cupertino_icons: ^1.0.2

  # Google dependencies
  google_sign_in: ^5.4.2

  # Firebase dependencies
  firebase_core: ^2.2.0
  cloud_firestore: ^4.0.5
  firebase_storage: ^11.0.5
  firebase_messaging: ^14.1.0
  firebase_auth: ^4.1.2
  cloud_functions: ^4.0.4
  firebase_crashlytics: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^5.0.2
  build_runner:
  json_serializable: ^6.4.0
  http: ^0.13.5
  isar_generator: ^3.0.1
  flutter_launcher_icons: ^0.10.0
  mockito: ^5.3.2
  firebase_storage_mocks: ^0.6.0+1
  firebase_auth_mocks: ^0.9.1
  google_sign_in_mocks: ^0.2.1
  fake_cloud_firestore: ^2.0.1

  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#000"
    theme_color: "#000"

flutter_native_splash:
  color: "#000000"
  image: assets/images/logo_whitex3.png
  android: true
  ios: true
  web: true
  android_gravity: center
  ios_content_mode: center
  web_image_mode: center
  fullscreen: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/bottom_bar/
    - assets/recipes.json
    - assets/search_not_found.json
